from __future__ import annotations

CASES = [
    {
        "cid": "KJ-01",
        "title": "首次打开快记：弹出同意授权窗",
        "module": "授权",
        "mode": "AUTO",
        "priority": "P0",
        "suite": "smoke",
        "steps": ["杀进程后打开听记", "看是否弹出同意授权窗", "点同意后窗关闭"],
        "asserts": ["弹出授权窗", "点同意后授权窗关闭"],
        "note": "已授权则记 SKIP",
    },
    {
        "cid": "KJ-02",
        "title": "允许麦克风、存储、通知授权：录音页开始计时",
        "module": "授权",
        "mode": "AUTO",
        "priority": "P0",
        "suite": "smoke",
        "steps": ["点开始录音", "处理运行时权限", "看录音页计时"],
        "asserts": ["进入录音或已授权", "计时开始"],
        "note": "已授权则直接看计时",
    },
    {
        "cid": "KJ-03",
        "title": "列表点录音：进入录音页并计时",
        "module": "录音",
        "mode": "AUTO",
        "priority": "P0",
        "suite": "smoke",
        "steps": ["回到列表", "点开始录音", "确认进入录音页并计时"],
        "asserts": ["进入录音页", "计时大于0"],
        "note": "点 content-desc「开始录音」，不要点 Tab「录音」",
    },
    {
        "cid": "KJ-04",
        "title": "暂停后点继续：从暂停点续录",
        "module": "录音",
        "mode": "AUTO",
        "priority": "P0",
        "suite": "smoke",
        "steps": ["录音中点暂停", "再点继续", "对比暂停前后秒数"],
        "asserts": ["暂停后计时停住", "继续后秒数不回零"],
        "note": "暂停坐标 (420,2420)",
    },
    {
        "cid": "KJ-05",
        "title": "点结束：列表出现文件且时长对",
        "module": "录音",
        "mode": "AUTO",
        "priority": "P0",
        "suite": "smoke",
        "steps": ["录约 10 秒", "点结束", "回列表看文件和时长"],
        "asserts": ["列表出现新文件", "时长与录音接近"],
        "note": "结束坐标 (750,2420)",
    },
    {
        "cid": "KJ-06",
        "title": "重命名保存：列表显示新文件名",
        "module": "文件",
        "mode": "AUTO",
        "priority": "P1",
        "suite": "smoke",
        "steps": ["长按列表标题", "点重命名", "输入 KJ06A", "保存"],
        "asserts": ["打开重命名", "列表显示 KJ06A"],
        "note": "中文输入法 adb 打不进去，固定 KJ06A",
    },
    {
        "cid": "KJ-07",
        "title": "删除确认后：文件从列表消失",
        "module": "文件",
        "mode": "AUTO",
        "priority": "P1",
        "suite": "smoke",
        "steps": ["长按「新录音」", "删除", "确认"],
        "asserts": ["弹出删除确认", "目标文件从列表消失"],
        "note": "优先删新录音，保留 KJ06A 给搜索",
    },
    {
        "cid": "KJ-08",
        "title": "选中后分享：拉起系统分享面板",
        "module": "文件",
        "mode": "AUTO",
        "priority": "P1",
        "suite": "smoke",
        "steps": ["长按一条录音", "点分享"],
        "asserts": ["点到分享", "拉起系统分享面板"],
        "note": "",
    },
    {
        "cid": "KJ-09",
        "title": "按文件名搜索：命中对应条目",
        "module": "文件",
        "mode": "AUTO",
        "priority": "P1",
        "suite": "smoke",
        "steps": ["点搜索", "输入 KJ06A"],
        "asserts": ["找到搜索入口", "搜索命中或空态"],
        "note": "搜索只有 content-desc",
    },
    {
        "cid": "KJ-10",
        "title": "通话自动录音开：挂断后列表有文件",
        "module": "通话录音",
        "mode": "MANUAL",
        "priority": "P1",
        "suite": "smoke",
        "steps": ["打开通话自动录音", "第二台机拨打接通≥8秒", "挂断后回列表"],
        "asserts": ["列表出现通话录音文件"],
        "note": "要第二台机，默认记 MANUAL",
    },
    {
        "cid": "KJ-11",
        "title": "点开关旁空白：开关不误翻转",
        "module": "通话录音",
        "mode": "AUTO",
        "priority": "P2",
        "suite": "smoke",
        "steps": ["设置 → 通话录音", "点「通话自动录音」文字左侧", "再点滑块"],
        "asserts": ["点空白/滑块未崩溃"],
        "note": "进通话录音会打开 callsetting",
    },
    {
        "cid": "KJ-12",
        "title": "卸载后在应用商店重装：旧录音不在列表",
        "module": "安装",
        "mode": "MANUAL",
        "priority": "P2",
        "suite": "smoke",
        "steps": ["卸载听记", "应用商店重装", "打开列表"],
        "asserts": ["旧录音不在列表"],
        "note": "会卸听记，默认记 MANUAL",
    },
]


def list_cases() -> list[dict]:
    return [dict(x) for x in CASES]


def get_case(cid: str) -> dict | None:
    for x in CASES:
        if x["cid"] == cid:
            return dict(x)
    return None
